name: App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.2

      - name: Build backend binary
        run: |
          cd api
          go build

      - name: Deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./api/main

  test_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2.1.2
      - uses: actions/checkout@v2

      - name: Test backend
        run: |
          cd api
          go test *.go -v
