name: Landing Page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ijustdev/jekyll-action@2.0.6
        env:
            JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
            GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        with:
            jekyll_src: 'website'
            custom_domain: 'openschool.dev'
